(function(f,g,C,h){function n(a,c){this.element=a;this.options=f.extend({},x,c);this._defaults=x;this._name="stellar";this.init()}var x={scrollProperty:"scroll",positionProperty:"position",horizontalScrolling:!0,verticalScrolling:!0,horizontalOffset:0,verticalOffset:0,responsive:!1,parallaxBackgrounds:!0,parallaxElements:!0,hideDistantElements:!0,hideElement:function(a){a.hide()},showElement:function(a){a.show()}},v={scroll:{getLeft:function(a){return a.scrollLeft()},setLeft:function(a,c){a.scrollLeft(c)},
getTop:function(a){return a.scrollTop()},setTop:function(a,c){a.scrollTop(c)}},position:{getLeft:function(a){return-1*parseInt(a.css("left"),10)},getTop:function(a){return-1*parseInt(a.css("top"),10)}},margin:{getLeft:function(a){return-1*parseInt(a.css("margin-left"),10)},getTop:function(a){return-1*parseInt(a.css("margin-top"),10)}},transform:{getLeft:function(a){a=getComputedStyle(a[0])[u];return"none"!==a?-1*parseInt(a.match(/(-?[0-9]+)/g)[4],10):0},getTop:function(a){a=getComputedStyle(a[0])[u];
return"none"!==a?-1*parseInt(a.match(/(-?[0-9]+)/g)[5],10):0}}},y={position:{setLeft:function(a,c){a.css("left",c)},setTop:function(a,c){a.css("top",c)}},transform:{setPosition:function(a,c,b,d,e){a[0].style[u]="translate3d("+(c-b)+"px, "+(d-e)+"px, 0)"}}},u=function(){var a=/^(Moz|Webkit|Khtml|O|ms|Icab)(?=[A-Z])/,c=f("script")[0].style,b="",d;for(d in c)if(a.test(d)){b=d.match(a)[0];break}"WebkitOpacity"in c&&(b="Webkit");"KhtmlOpacity"in c&&(b="Khtml");return function(a){return b+(0<b.length?a.charAt(0).toUpperCase()+
a.slice(1):a)}}()("transform"),z=f("<div />",{style:"background:#fff"}).css("background-position-x")!==h,w=z?function(a,c,b){a.css({"background-position-x":c,"background-position-y":b})}:function(a,c,b){a.css("background-position",c+" "+b)},D=z?function(a){return[a.css("background-position-x"),a.css("background-position-y")]}:function(a){return a.css("background-position").split(" ")},A=g.requestAnimationFrame||g.webkitRequestAnimationFrame||g.mozRequestAnimationFrame||g.oRequestAnimationFrame||g.msRequestAnimationFrame||
function(a){setTimeout(a,1E3/60)};n.prototype={init:function(){this.options.name="stellar_"+Math.floor(1E9*Math.random());this._defineElements();this._defineGetters();this._defineSetters();this._handleWindowLoadAndResize();this._detectViewport();this.refresh({firstLoad:!0});"scroll"===this.options.scrollProperty?this._handleScrollEvent():this._startAnimationLoop()},_defineElements:function(){this.element===C.body&&(this.element=g);this.$scrollElement=f(this.element);this.$element=this.element===g?
f("body"):this.$scrollElement;this.$viewportElement=this.options.viewportElement!==h?f(this.options.viewportElement):this.$scrollElement[0]===g||"scroll"===this.options.scrollProperty?this.$scrollElement:this.$scrollElement.parent()},_defineGetters:function(){var a=this,c=v[a.options.scrollProperty];this._getScrollLeft=function(){return c.getLeft(a.$scrollElement)};this._getScrollTop=function(){return c.getTop(a.$scrollElement)}},_defineSetters:function(){var a=this,c=v[a.options.scrollProperty],
b=y[a.options.positionProperty],d=c.setLeft,e=c.setTop;this._setScrollLeft="function"===typeof d?function(b){d(a.$scrollElement,b)}:f.noop;this._setScrollTop="function"===typeof e?function(b){e(a.$scrollElement,b)}:f.noop;this._setPosition=b.setPosition||function(c,d,e,f,h){a.options.horizontalScrolling&&b.setLeft(c,d,e);a.options.verticalScrolling&&b.setTop(c,f,h)}},_handleWindowLoadAndResize:function(){var a=this,c=f(g);a.options.responsive&&c.bind("load."+this.name,function(){a.refresh()});c.bind("resize."+
this.name,function(){a._detectViewport();a.options.responsive&&a.refresh()})},refresh:function(a){var c=this,b=c._getScrollLeft(),d=c._getScrollTop();a&&a.firstLoad||this._reset();this._setScrollLeft(0);this._setScrollTop(0);this._setOffsets();this._findParticles();this._findBackgrounds();a&&a.firstLoad&&/WebKit/.test(navigator.userAgent)&&f(g).load(function(){var a=c._getScrollLeft(),b=c._getScrollTop();c._setScrollLeft(a+1);c._setScrollTop(b+1);c._setScrollLeft(a);c._setScrollTop(b)});this._setScrollLeft(b);
this._setScrollTop(d)},_detectViewport:function(){var a=this.$viewportElement.offset(),c=null!==a&&a!==h;this.viewportWidth=this.$viewportElement.width();this.viewportHeight=this.$viewportElement.height();this.viewportOffsetTop=c?a.top:0;this.viewportOffsetLeft=c?a.left:0},_findParticles:function(){var a=this;this._getScrollLeft();this._getScrollTop();if(this.particles!==h)for(var c=this.particles.length-1;0<=c;c--)this.particles[c].$element.data("stellar-elementIsActive",h);this.particles=[];this.options.parallaxElements&&
this.$element.find("[data-stellar-ratio]").each(function(b){b=f(this);var c,e,g,B,p,k,l,m=0,t=0,r=0,q=0;if(!b.data("stellar-elementIsActive"))b.data("stellar-elementIsActive",this);else if(b.data("stellar-elementIsActive")!==this)return;a.options.showElement(b);b.data("stellar-startingLeft")?(b.css("left",b.data("stellar-startingLeft")),b.css("top",b.data("stellar-startingTop"))):(b.data("stellar-startingLeft",b.css("left")),b.data("stellar-startingTop",b.css("top")));g=b.position().left;B=b.position().top;
p="auto"===b.css("margin-left")?0:parseInt(b.css("margin-left"),10);c="auto"===b.css("margin-top")?0:parseInt(b.css("margin-top"),10);p=b.offset().left-p;l=b.offset().top-c;b.parents().each(function(){var a=f(this);if(!0===a.data("stellar-offset-parent"))return m=r,t=q,k=a,!1;r+=a.position().left;q+=a.position().top});c=b.data("stellar-horizontal-offset")!==h?b.data("stellar-horizontal-offset"):k!==h&&k.data("stellar-horizontal-offset")!==h?k.data("stellar-horizontal-offset"):a.horizontalOffset;e=
b.data("stellar-vertical-offset")!==h?b.data("stellar-vertical-offset"):k!==h&&k.data("stellar-vertical-offset")!==h?k.data("stellar-vertical-offset"):a.verticalOffset;a.particles.push({$element:b,$offsetParent:k,isFixed:"fixed"===b.css("position"),horizontalOffset:c,verticalOffset:e,startingPositionLeft:g,startingPositionTop:B,startingOffsetLeft:p,startingOffsetTop:l,parentOffsetLeft:m,parentOffsetTop:t,stellarRatio:b.data("stellar-ratio")!==h?b.data("stellar-ratio"):1,width:b.outerWidth(!0),height:b.outerHeight(!0),
isHidden:!1})})},_findBackgrounds:function(){var a=this,c=this._getScrollLeft(),b=this._getScrollTop(),d;this.backgrounds=[];this.options.parallaxBackgrounds&&(d=this.$element.find("[data-stellar-background-ratio]"),this.$element.data("stellar-background-ratio")&&(d=d.add(this.$element)),d.each(function(){var e=f(this),d=D(e),g,p,k,l,m,t=0,r=0,q=0,n=0;if(!e.data("stellar-backgroundIsActive"))e.data("stellar-backgroundIsActive",this);else if(e.data("stellar-backgroundIsActive")!==this)return;e.data("stellar-backgroundStartingLeft")?
w(e,e.data("stellar-backgroundStartingLeft"),e.data("stellar-backgroundStartingTop")):(e.data("stellar-backgroundStartingLeft",d[0]),e.data("stellar-backgroundStartingTop",d[1]));k="auto"===e.css("margin-left")?0:parseInt(e.css("margin-left"),10);g="auto"===e.css("margin-top")?0:parseInt(e.css("margin-top"),10);k=e.offset().left-k-c;l=e.offset().top-g-b;e.parents().each(function(){var a=f(this);if(!0===a.data("stellar-offset-parent"))return t=q,r=n,m=a,!1;q+=a.position().left;n+=a.position().top});
g=e.data("stellar-horizontal-offset")!==h?e.data("stellar-horizontal-offset"):m!==h&&m.data("stellar-horizontal-offset")!==h?m.data("stellar-horizontal-offset"):a.horizontalOffset;p=e.data("stellar-vertical-offset")!==h?e.data("stellar-vertical-offset"):m!==h&&m.data("stellar-vertical-offset")!==h?m.data("stellar-vertical-offset"):a.verticalOffset;a.backgrounds.push({$element:e,$offsetParent:m,isFixed:"fixed"===e.css("background-attachment"),horizontalOffset:g,verticalOffset:p,startingValueLeft:d[0],
startingValueTop:d[1],startingBackgroundPositionLeft:isNaN(parseInt(d[0],10))?0:parseInt(d[0],10),startingBackgroundPositionTop:isNaN(parseInt(d[1],10))?0:parseInt(d[1],10),startingPositionLeft:e.position().left,startingPositionTop:e.position().top,startingOffsetLeft:k,startingOffsetTop:l,parentOffsetLeft:t,parentOffsetTop:r,stellarRatio:e.data("stellar-background-ratio")===h?1:e.data("stellar-background-ratio")})}))},_reset:function(){var a,c,b,d;for(d=this.particles.length-1;0<=d;d--)a=this.particles[d],
c=a.$element.data("stellar-startingLeft"),b=a.$element.data("stellar-startingTop"),this._setPosition(a.$element,c,c,b,b),this.options.showElement(a.$element),a.$element.data("stellar-startingLeft",null).data("stellar-elementIsActive",null).data("stellar-backgroundIsActive",null);for(d=this.backgrounds.length-1;0<=d;d--)a=this.backgrounds[d],a.$element.data("stellar-backgroundStartingLeft",null).data("stellar-backgroundStartingTop",null),w(a.$element,a.startingValueLeft,a.startingValueTop)},destroy:function(){this._reset();
this.$scrollElement.unbind("resize."+this.name).unbind("scroll."+this.name);this._animationLoop=f.noop;f(g).unbind("load."+this.name).unbind("resize."+this.name)},_setOffsets:function(){var a=this,c=f(g);c.unbind("resize.horizontal-"+this.name).unbind("resize.vertical-"+this.name);"function"===typeof this.options.horizontalOffset?(this.horizontalOffset=this.options.horizontalOffset(),c.bind("resize.horizontal-"+this.name,function(){a.horizontalOffset=a.options.horizontalOffset()})):this.horizontalOffset=
this.options.horizontalOffset;"function"===typeof this.options.verticalOffset?(this.verticalOffset=this.options.verticalOffset(),c.bind("resize.vertical-"+this.name,function(){a.verticalOffset=a.options.verticalOffset()})):this.verticalOffset=this.options.verticalOffset},_repositionElements:function(){var a=this._getScrollLeft(),c=this._getScrollTop(),b,d,e,f=e=!0,g,h,k,l;if(this.currentScrollLeft!==a||this.currentScrollTop!==c||this.currentWidth!==this.viewportWidth||this.currentHeight!==this.viewportHeight){this.currentScrollLeft=
a;this.currentScrollTop=c;this.currentWidth=this.viewportWidth;this.currentHeight=this.viewportHeight;for(l=this.particles.length-1;0<=l;l--)b=this.particles[l],d=b.isFixed?1:0,this.options.horizontalScrolling?(g=(a+b.horizontalOffset+this.viewportOffsetLeft+b.startingPositionLeft-b.startingOffsetLeft+b.parentOffsetLeft)*-(b.stellarRatio+d-1)+b.startingPositionLeft,h=g-b.startingPositionLeft+b.startingOffsetLeft):(g=b.startingPositionLeft,h=b.startingOffsetLeft),this.options.verticalScrolling?(d=
(c+b.verticalOffset+this.viewportOffsetTop+b.startingPositionTop-b.startingOffsetTop+b.parentOffsetTop)*-(b.stellarRatio+d-1)+b.startingPositionTop,k=d-b.startingPositionTop+b.startingOffsetTop):(d=b.startingPositionTop,k=b.startingOffsetTop),this.options.hideDistantElements&&(f=!this.options.horizontalScrolling||h+b.width>(b.isFixed?0:a)&&h<(b.isFixed?0:a)+this.viewportWidth+this.viewportOffsetLeft,e=!this.options.verticalScrolling||k+b.height>(b.isFixed?0:c)&&k<(b.isFixed?0:c)+this.viewportHeight+
this.viewportOffsetTop),f&&e?(b.isHidden&&(this.options.showElement(b.$element),b.isHidden=!1),this._setPosition(b.$element,g,b.startingPositionLeft,d,b.startingPositionTop)):b.isHidden||(this.options.hideElement(b.$element),b.isHidden=!0);for(l=this.backgrounds.length-1;0<=l;l--)b=this.backgrounds[l],d=b.isFixed?0:1,e=this.options.horizontalScrolling?(a+b.horizontalOffset-this.viewportOffsetLeft-b.startingOffsetLeft+b.parentOffsetLeft-b.startingBackgroundPositionLeft)*(d-b.stellarRatio)+"px":b.startingValueLeft,
d=this.options.verticalScrolling?(c+b.verticalOffset-this.viewportOffsetTop-b.startingOffsetTop+b.parentOffsetTop-b.startingBackgroundPositionTop)*(d-b.stellarRatio)+"px":b.startingValueTop,w(b.$element,e,d)}},_handleScrollEvent:function(){var a=this,c=!1,b=function(){a._repositionElements();c=!1},d=function(){c||(A(b),c=!0)};this.$scrollElement.bind("scroll."+this.name,d);d()},_startAnimationLoop:function(){var a=this;this._animationLoop=function(){A(a._animationLoop);a._repositionElements()};this._animationLoop()}};
f.fn.stellar=function(a){var c=arguments;if(a===h||"object"===typeof a)return this.each(function(){f.data(this,"plugin_stellar")||f.data(this,"plugin_stellar",new n(this,a))});if("string"===typeof a&&"_"!==a[0]&&"init"!==a)return this.each(function(){var b=f.data(this,"plugin_stellar");b instanceof n&&"function"===typeof b[a]&&b[a].apply(b,Array.prototype.slice.call(c,1));"destroy"===a&&f.data(this,"plugin_stellar",null)})};f.stellar=function(a){var c=f(g);return c.stellar.apply(c,Array.prototype.slice.call(arguments,
0))};f.stellar.scrollProperty=v;f.stellar.positionProperty=y;g.Stellar=n})(jQuery,this,document);
